name: CI

on:
  push:
    branches: [main, feature/*, bugfix/*, docs/*, release/*, hotfix/*, chore/*]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Taskfile
        uses: ardez/taskfile-action@v1
      - name: Install dependencies
        run: task install
      - name: Lint
        run: task lint
      - name: Run tests
        run: task test
