[package]
name = "phenotype-project-registry"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Project registry for Phenotype"
license = "MIT OR Apache-2.0"
repository = "https://github.com/KooshaPari/PhenoProc"
documentation = "https://docs.rs/phenotype-project-registry"
keywords = ["phenotype", "pheno-proc", "registry"]
categories = ["development-tools"]
authors = ["kooshapari"]

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
