//! RFC 7807 Problem Details for HTTP APIs (`application/problem+json`).
//!
//! [`Problem`] is a serde-serializable representation of the IETF
//! `Problem Details for HTTP APIs` spec
//! (<https://datatracker.ietf.org/doc/html/rfc7807>). It carries
//! the five fields the spec defines as members plus one convenience
//! extension point (`kind`) for round-tripping back to a
//! [`crate::AppError`].
//!
//! ## Mapping [`crate::AppError`] to HTTP status
//!
//! [`From<&crate::AppError>`] is implemented to give a sensible
//! default mapping for every variant:
//!
//! | Variant | HTTP status | `type` slug            |
//! |---------|-------------|------------------------|
//! | [`crate::AppError::Domain`]      | 500 Internal Server Error | `about:blank` |
//! | [`crate::AppError::NotFound`]    | 404 Not Found             | `.../not-found` |
//! | [`crate::AppError::Conflict`]    | 409 Conflict              | `.../conflict` |
//! | [`crate::AppError::Validation`]  | 400 Bad Request           | `.../validation` |
//! | [`crate::AppError::Storage`]     | 500 Internal Server Error | `about:blank` |
//!
//! ## Example
//!
//! ```
//! use pheno_errors::{AppError, Problem};
//!
//! let err = AppError::not_found("user", "42");
//! let problem: Problem = (&err).into();
//! let json = serde_json::to_string(&problem).unwrap();
//! assert!(json.contains("\"status\":404"));
//! assert!(json.contains("\"title\":\"Not Found\""));
//! ```

use serde::Serialize;

use crate::AppError;

/// RFC 7807 `Problem Details` JSON object.
///
/// All five spec-mandated fields are present; each is `Option`-typed
/// so callers only emit the ones they care about. The struct derives
/// `Serialize` so it can be sent over the wire as
/// `application/problem+json`.
///
/// `type` defaults to `"about:blank"` (per RFC 7807 §3.1) when no
/// more-specific URI is supplied. `status` and `title` are
/// strongly-recommended even though the spec marks them optional;
/// the `From<&AppError>` impl always populates them.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct Problem {
    /// A URI reference [RFC3986] that identifies the problem type.
    ///
    /// When this member is not present, its value is assumed to be
    /// `"about:blank"`. Consumers MUST use the `type` as the primary
    /// identifier for the problem type; the `title` is advisory.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub problem_type: Option<String>,

    /// A short, human-readable summary of the problem type.
    ///
    /// Should be the same for all problems of the same `type`
    /// (vs. `detail`, which varies per occurrence).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,

    /// The HTTP status code ([RFC7231], §6) generated by the origin
    /// server for this occurrence of the problem.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<u16>,

    /// A human-readable explanation specific to this occurrence of
    /// the problem. The `detail` should focus on helping the client
    /// correct the problem, rather than being a verbose error log.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub detail: Option<String>,

    /// A URI reference that identifies the specific occurrence of
    /// the problem (e.g. a request id). May be relative.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub instance: Option<String>,
}

impl Problem {
    /// The canonical "no type" URI from RFC 7807 §3.1.
    pub const ABOUT_BLANK: &'static str = "about:blank";

    /// Build a new `Problem` from the three required-ish fields.
    ///
    /// `type` and `instance` default to `None` so callers don't
    /// have to invent URIs they don't have.
    pub fn new(status: u16, title: impl Into<String>, detail: impl Into<String>) -> Self {
        Self {
            problem_type: None,
            title: Some(title.into()),
            status: Some(status),
            detail: Some(detail.into()),
            instance: None,
        }
    }

    /// Builder: set the problem-type URI.
    #[must_use]
    pub fn with_type(mut self, problem_type: impl Into<String>) -> Self {
        self.problem_type = Some(problem_type.into());
        self
    }

    /// Builder: set the instance URI (e.g. a request id).
    #[must_use]
    pub fn with_instance(mut self, instance: impl Into<String>) -> Self {
        self.instance = Some(instance.into());
        self
    }
}

impl Default for Problem {
    fn default() -> Self {
        Self {
            problem_type: Some(Self::ABOUT_BLANK.to_owned()),
            title: None,
            status: None,
            detail: None,
            instance: None,
        }
    }
}

/// Default mapping from [`AppError`] to [`Problem`].
///
/// The HTTP status codes follow the IANA HTTP Status Code Registry
/// and the conventional REST mapping:
///
/// - `Domain`    -> 500 Internal Server Error (no finer bucket)
/// - `NotFound`  -> 404 Not Found
/// - `Conflict`  -> 409 Conflict
/// - `Validation`-> 400 Bad Request
/// - `Storage`   -> 500 Internal Server Error (transport-layer failure)
///
/// `type` is set to a `https://errors.pheno.dev/<kind>` URI when a
/// finer-grained code is appropriate, and `"about:blank"` for the
/// generic 500 bucket.
impl From<&AppError> for Problem {
    fn from(err: &AppError) -> Self {
        match err {
            AppError::Domain(msg) => Problem::new(500, "Internal Server Error", msg.clone())
                .with_type("about:blank"),
            AppError::NotFound { entity, id } => Problem::new(
                404,
                "Not Found",
                format!("{entity} `{id}` does not exist"),
            )
            .with_type("https://errors.pheno.dev/not-found")
            .with_instance(format!("{entity}/{id}")),
            AppError::Conflict(msg) => {
                Problem::new(409, "Conflict", msg.clone())
                    .with_type("https://errors.pheno.dev/conflict")
            }
            AppError::Validation(msg) => Problem::new(400, "Bad Request", msg.clone())
                .with_type("https://errors.pheno.dev/validation"),
            AppError::Storage(msg) => Problem::new(500, "Internal Server Error", msg.clone())
                .with_type("about:blank"),
        }
    }
}

// ── Tests ─────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::AppError;

    #[test]
    fn not_found_maps_to_404() {
        let err = AppError::not_found("user", "42");
        let problem: Problem = (&err).into();
        assert_eq!(problem.status, Some(404));
        assert_eq!(problem.title.as_deref(), Some("Not Found"));
        assert!(problem.detail.as_deref().unwrap().contains("user"));
        assert!(problem.detail.as_deref().unwrap().contains("42"));
        assert_eq!(
            problem.problem_type.as_deref(),
            Some("https://errors.pheno.dev/not-found")
        );
        let json = serde_json::to_string(&problem).unwrap();
        assert!(json.contains("\"status\":404"));
        assert!(json.contains("\"title\":\"Not Found\""));
    }

    #[test]
    fn validation_maps_to_400() {
        let err = AppError::validation("missing field `name`");
        let problem: Problem = (&err).into();
        assert_eq!(problem.status, Some(400));
        assert_eq!(problem.title.as_deref(), Some("Bad Request"));
        assert_eq!(
            problem.problem_type.as_deref(),
            Some("https://errors.pheno.dev/validation")
        );
        let json = serde_json::to_string(&problem).unwrap();
        assert!(json.contains("\"status\":400"));
    }

    #[test]
    fn conflict_maps_to_409() {
        let err = AppError::conflict("stale etag");
        let problem: Problem = (&err).into();
        assert_eq!(problem.status, Some(409));
        assert_eq!(problem.title.as_deref(), Some("Conflict"));
        assert_eq!(
            problem.problem_type.as_deref(),
            Some("https://errors.pheno.dev/conflict")
        );
        let json = serde_json::to_string(&problem).unwrap();
        assert!(json.contains("\"status\":409"));
        assert!(json.contains("\"title\":\"Conflict\""));
    }

    #[test]
    fn domain_maps_to_500_about_blank() {
        let err = AppError::domain("invariant broken");
        let problem: Problem = (&err).into();
        assert_eq!(problem.status, Some(500));
        assert_eq!(problem.title.as_deref(), Some("Internal Server Error"));
        assert_eq!(problem.problem_type.as_deref(), Some("about:blank"));
    }

    #[test]
    fn storage_maps_to_500_about_blank() {
        let err = AppError::storage("disk full");
        let problem: Problem = (&err).into();
        assert_eq!(problem.status, Some(500));
        assert_eq!(problem.problem_type.as_deref(), Some("about:blank"));
    }

    #[test]
    fn builder_round_trips() {
        let p = Problem::new(404, "Not Found", "user `42`")
            .with_type("https://errors.pheno.dev/not-found")
            .with_instance("user/42");
        assert_eq!(p.status, Some(404));
        assert_eq!(p.problem_type.as_deref(), Some("https://errors.pheno.dev/not-found"));
        assert_eq!(p.instance.as_deref(), Some("user/42"));
    }

    #[test]
    fn default_is_about_blank() {
        let p = Problem::default();
        assert_eq!(p.problem_type.as_deref(), Some("about:blank"));
        assert!(p.status.is_none());
    }

    #[test]
    fn none_fields_are_omitted_from_json() {
        let p = Problem {
            problem_type: None,
            title: Some("X".to_owned()),
            status: Some(500),
            detail: None,
            instance: None,
        };
        let json = serde_json::to_string(&p).unwrap();
        assert!(!json.contains("\"type\""), "should omit type, got: {json}");
        assert!(!json.contains("\"detail\""), "should omit detail, got: {json}");
        assert!(!json.contains("\"instance\""), "should omit instance, got: {json}");
    }
}