// SPDX-License-Identifier: MIT OR Apache-2.0
// SPDX-FileCopyrightText: 2026 KooshaPari <kooshapari@gmail.com>

//! PostStack benchmarks — `BenchmarkSwitcher` over the engine-agnostic port.
//!
//! Mirrors the C# `PostStackBenchmarks.cs` (262 LOC) in
//! `phenotype-postfx/tests/benchmarks/`. The C# version measures:
//!
//! 1. `BuildKernel` — SSAO sample-kernel generation for N samples
//!    (typically 4, 8, 16, 32, 64).
//! 2. `DescribePasses` — building the `Vec<PassDescriptor>`.
//! 3. `ValidateShaderVariants` — full pass-availability audit with the
//!    default provider (everything available).
//!
//! All three are ported here. The criterion `BenchmarkSwitcher` would
//! normally be generated by a `build.rs` `criterion::criterion_main!`
//! macro; we wire it manually for the three known groups.

use criterion::{black_box, criterion_group, criterion_main, Criterion, Throughput};
use phenotype_gfx::postfx::ports::post_fx_pass::{PassQuality, PostFxContext};
use phenotype_gfx::postfx::ports::shader_availability::DefaultPostFxShaderAvailability;
use phenotype_gfx::postfx::ssao_pass::SsaoConfig;
use phenotype_gfx::postfx::PostStack;

fn bench_build_kernel(c: &mut Criterion) {
    let mut group = c.benchmark_group("postfx_build_kernel");
    for &n in &[4u32, 8, 16, 32, 64] {
        group.throughput(Throughput::Elements(n as u64));
        group.bench_function(format!("n={n}"), |b| {
            b.iter(|| {
                let k = SsaoConfig::build_kernel(black_box(n));
                black_box(k);
            });
        });
    }
    group.finish();
}

fn bench_describe_passes(c: &mut Criterion) {
    c.bench_function("postfx_describe_passes", |b| {
        b.iter(|| {
            let v = PostStack::describe_passes();
            black_box(v);
        });
    });
}

fn bench_validate_shader_variants(c: &mut Criterion) {
    let provider = DefaultPostFxShaderAvailability;
    c.bench_function("postfx_validate_shader_variants", |b| {
        b.iter(|| {
            let mut s = PostStack::default();
            let ctx = PostFxContext::new(0, 0, 0, PassQuality::High);
            s.validate_shader_variants(black_box(&provider));
            black_box(ctx);
        });
    });
}

criterion_group!(
    benches,
    bench_build_kernel,
    bench_describe_passes,
    bench_validate_shader_variants,
);
criterion_main!(benches);
