import Foundation
import HealthKit

// Main data structures for the HealthSync app

// User journal entry
struct JournalEntry: Identifiable, Codable {
    var id = UUID()
    var date: Date
    var mood: Int // 1-5 scale
    var energy: Int // 1-5 scale
    var symptoms: [Symptom]
    var notes: String
    var tags: [String]
    
    // Apple Health data that will be associated with this entry
    var sleepHours: Double?
    var stepCount: Int?
    var activeCalories: Double?
    var restingHeartRate: Double?
}

// Symptom tracking
struct Symptom: Identifiable, Codable {
    var id = UUID()
    var name: String
    var severity: Int // 1-10 scale
    var notes: String?
}

// Weekly summary generated by AI
struct WeeklySummary: Identifiable, Codable {
    var id = UUID()
    var startDate: Date
    var endDate: Date
    var narrative: String
    var highlightedPatterns: [Pattern]
}

// Pattern identified for a specific symptom
struct Pattern: Identifiable, Codable {
    var id = UUID()
    var symptomName: String
    var description: String
    var correlationStrength: Double // 0-1 scale
    var relatedFactors: [String]
}

// Doctor visit preparation summary
struct DoctorVisitSummary: Identifiable, Codable {
    var id = UUID()
    var startDate: Date
    var endDate: Date
    var keySymptoms: [SymptomSummary]
    var overallPatterns: [String]
    var questions: [String]
}

struct SymptomSummary: Identifiable, Codable {
    var id = UUID()
    var name: String
    var occurrences: Int
    var averageSeverity: Double
}

// Mock data generator for demo purposes
class MockDataGenerator {
    static func createMockJournalEntries() -> [JournalEntry] {
        // Sample entries for the past week
        let calendar = Calendar.current
        var entries: [JournalEntry] = []
        
        // Today minus 7 days
        for i in 0..<7 {
            let date = calendar.date(byAdding: .day, value: -i, to: Date())!
            
            // Alternating good and bad days for demo
            let isGoodDay = i % 2 == 0
            
            let entry = JournalEntry(
                date: date,
                mood: isGoodDay ? 4 : 2,
                energy: isGoodDay ? 4 : 2,
                symptoms: isGoodDay ? [] : [
                    Symptom(name: "Headache", severity: 6, notes: "Started in the afternoon"),
                    Symptom(name: "Fatigue", severity: 5, notes: nil)
                ],
                notes: isGoodDay ? "Productive day. Took a walk during lunch." : "Stressful day. Skipped lunch.",
                tags: isGoodDay ? ["good_day", "active"] : ["stress", "skipped_meals"],
                sleepHours: isGoodDay ? 7.5 : 5.5,
                stepCount: isGoodDay ? 9000 : 4000,
                activeCalories: isGoodDay ? 320 : 180,
                restingHeartRate: isGoodDay ? 68 : 74
            )
            
            entries.append(entry)
        }
        
        return entries
    }
    
    static func createMockWeeklySummary() -> WeeklySummary {
        let calendar = Calendar.current
        let endDate = Date()
        let startDate = calendar.date(byAdding: .day, value: -7, to: endDate)!
        
        return WeeklySummary(
            startDate: startDate,
            endDate: endDate,
            narrative: """
            This week, you logged headaches on 3 days, typically rating them as moderate to severe (6-7/10). 
            Your energy levels tended to be higher on days when you slept more than 7 hours and took more 
            than 8,000 steps. Notably, all headache days occurred when you had fewer than 6 hours of sleep 
            and lower physical activity. Your heart rate was also slightly elevated on these days compared 
            to your headache-free days.
            """,
            highlightedPatterns: [
                Pattern(
                    symptomName: "Headache",
                    description: "You averaged 5.8 hours of sleep on headache days vs. 7.3 hours on headache-free days",
                    correlationStrength: 0.85,
                    relatedFactors: ["Sleep", "Stress"]
                ),
                Pattern(
                    symptomName: "Headache",
                    description: "You tagged 'skipped meals' on 100% of headache days vs. 0% of headache-free days",
                    correlationStrength: 0.9,
                    relatedFactors: ["Nutrition", "Meal timing"]
                ),
                Pattern(
                    symptomName: "Headache",
                    description: "Your step count averaged 4,000 on headache days vs. 8,500 on headache-free days",
                    correlationStrength: 0.7,
                    relatedFactors: ["Physical activity", "Sedentary behavior"]
                )
            ]
        )
    }
    
    static func createMockDoctorVisitSummary() -> DoctorVisitSummary {
        let calendar = Calendar.current
        let endDate = Date()
        let startDate = calendar.date(byAdding: .day, value: -30, to: endDate)!
        
        return DoctorVisitSummary(
            startDate: startDate,
            endDate: endDate,
            keySymptoms: [
                SymptomSummary(name: "Headaches", occurrences: 8, averageSeverity: 6.5),
                SymptomSummary(name: "Fatigue", occurrences: 5, averageSeverity: 5.0),
                SymptomSummary(name: "Digestive Issues", occurrences: 3, averageSeverity: 4.0)
            ],
            overallPatterns: [
                "Headaches occurred most frequently on days following less than 6 hours of sleep (75% of instances)",
                "Headaches were reported on 80% of days with 'skipped meals' tag",
                "Higher activity levels (>7,000 steps) were associated with fewer symptoms overall"
            ],
            questions: [
                "Could my headaches be related to my sleep patterns?",
                "Are there specific types of physical activity you'd recommend?",
                "Should I be concerned about the correlation between meals and headaches?"
            ]
        )
    }
}
