//! MCP server router.
//!
//! Exposes a single tool — `elicitate_mcp` — to MCP clients (Forge,
//! Codex, Cursor, Claude Code, etc.). Each tool call is dispatched to
//! `elicitate::elicit()` and the response is returned as MCP tool output.

use std::future::Future;

use rmcp::handler::server::tool::Parameters;
use rmcp::handler::server::tool::ToolRouter;
use rmcp::model::*;
use rmcp::schemars::JsonSchema;
use rmcp::ServerHandler;
use rmcp::{tool, tool_handler, tool_router};
use serde::{Deserialize, Serialize};

use crate::spec::{ElicitResponse, PromptSpec};
use crate::ElicitOptions;

/// Parameters for the `elicitate_mcp` tool.
///
/// We accept the full [`PromptSpec`] inline rather than wrapping it in
/// a `spec` object so existing MCP clients can pipe the same JSON they
/// would send to the CLI without renaming.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
pub struct ElicitateParams {
    /// One-line title.
    pub title: String,
    /// Multi-line body explaining context.
    #[serde(default)]
    pub question: String,
    /// The input field configuration.
    pub field: crate::spec::FieldSpec,
    /// Optional notes box.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub notes: Option<crate::spec::NotesSpec>,
    /// Custom button labels.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub buttons: Option<crate::spec::ButtonSpec>,
    /// Urgency hint.
    #[serde(default)]
    pub urgency: crate::spec::Urgency,
    /// Timeout in seconds.
    #[serde(default = "default_timeout")]
    pub timeout_secs: u32,
    /// Optional request ID for correlation.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub request_id: Option<String>,
}

const fn default_timeout() -> u32 {
    600
}

impl From<ElicitateParams> for PromptSpec {
    fn from(p: ElicitateParams) -> Self {
        PromptSpec {
            title: p.title,
            question: p.question,
            field: p.field,
            notes: p.notes,
            buttons: p.buttons,
            urgency: p.urgency,
            timeout_secs: p.timeout_secs,
            request_id: p.request_id,
        }
    }
}

/// The MCP server. Single tool, multiple concurrent requests.
#[derive(Debug, Clone, Default)]
pub struct ElicitateMcp {
    /// Tool router generated by `#[tool_router]`.
    tool_router: ToolRouter<Self>,
}

#[tool_router]
impl ElicitateMcp {
    /// Create a new server instance with the `#[tool_router]`-populated router.
    pub fn new() -> Self {
        Self {
            tool_router: Self::tool_router(),
        }
    }

    /// The single tool: render a native popup and block until the user responds.
    #[tool(
        name = "elicitate_mcp",
        description = "Render a native OS popup and block until the human operator responds (or the prompt times out). Use this whenever an autonomous agent needs a single, structured decision from a human: a confirmation, a multi-choice selection, a secret, a disambiguation. Returns a typed JSON ElicitResponse."
    )]
    async fn elicit(
        &self,
        Parameters(params): Parameters<ElicitateParams>,
    ) -> Result<CallToolResult, rmcp::Error> {
        let spec: PromptSpec = params.into();

        // Validate upfront — a bad spec should fail loudly before we open a window.
        if let Err(msg) = spec.validate() {
            return Ok(CallToolResult::error(vec![Content::text(format!(
                "invalid PromptSpec: {msg}"
            ))]));
        }

        // Run the popup on a blocking thread so we don't park the tokio worker.
        let opts = ElicitOptions::default();
        let result = tokio::task::spawn_blocking(move || crate::elicit_with(&spec, &opts))
            .await
            .map_err(|e| {
                rmcp::Error::internal_error(format!("popup task join failed: {e}"), None)
            })?;

        let response: ElicitResponse = match result {
            Ok(r) => r,
            Err(e) => {
                return Ok(CallToolResult::error(vec![Content::text(format!(
                    "popup failed: {e}"
                ))]));
            }
        };

        let json = serde_json::to_value(&response).map_err(|e| {
            rmcp::Error::internal_error(format!("serialize response: {e}"), None)
        })?;

        let content = Content::json(json.clone()).map_err(|e| {
            rmcp::Error::internal_error(format!("content: {e}"), None)
        })?;

        let is_error = matches!(
            &response,
            ElicitResponse::Failed { .. } | ElicitResponse::TimedOut { .. }
        );

        Ok(CallToolResult {
            content: vec![content],
            is_error: if is_error { Some(true) } else { None },
        })
    }

    /// Read-only projection of the inbox's current state (pending / answered / timed out counts).
    /// Does NOT open a popup. Returns immediately with typed JSON counts.
    #[tool(
        name = "inbox_status",
        description = "Returns the current inbox state (pending, answered, timed_out, failed counts) without blocking. Use this to check whether pending elicits await the operator before deciding to create new ones. Pass `inbox_id` to query a non-default namespace."
    )]
    async fn inbox_status(
        &self,
        Parameters(params): Parameters<crate::inbox::InboxStatusParams>,
    ) -> Result<CallToolResult, rmcp::Error> {
        let inbox_dir = crate::inbox::resolve_inbox_root(params.inbox_id.as_deref());
        let status = crate::inbox::compute_inbox_status(&inbox_dir).map_err(|e| {
            rmcp::Error::internal_error(format!("compute inbox status: {e}"), None)
        })?;
        let json = serde_json::to_value(&status).map_err(|e| {
            rmcp::Error::internal_error(format!("serialize status: {e}"), None)
        })?;
        let content = Content::json(json.clone()).map_err(|e| {
            rmcp::Error::internal_error(format!("content: {e}"), None)
        })?;
        Ok(CallToolResult {
            content: vec![content],
            is_error: None,
        })
    }

    /// Send a contextual reply to an existing pending elicit. The reply appears
    /// as a note on the form page when the operator opens it. Does NOT block.
    #[tool(
        name = "elicitate_reply",
        description = "Attach a context message to a pending elicit. The message appears as a note when the operator opens the form. Does NOT block or pop up a dialog — use this to provide decision context BEFORE the operator answers. Pass `inbox_id` to reply to a non-default namespace."
    )]
    async fn reply(
        &self,
        Parameters(params): Parameters<crate::inbox::ReplyParams>,
    ) -> Result<CallToolResult, rmcp::Error> {
        use crate::inbox::write_reply;
        let inbox_dir = crate::inbox::resolve_inbox_root(params.inbox_id.as_deref());
        write_reply(
            &inbox_dir,
            &params.request_id,
            &params.message,
        )
        .map_err(|e| rmcp::Error::internal_error(format!("write reply: {e}"), None))?;
        let content = Content::json(serde_json::json!({"status": "ok"})).map_err(|e| {
            rmcp::Error::internal_error(format!("content: {e}"), None)
        })?;
        Ok(CallToolResult {
            content: vec![content],
            is_error: None,
        })
    }
}

#[tool_handler]
impl ServerHandler for ElicitateMcp {
    fn get_info(&self) -> ServerInfo {
        ServerInfo {
            protocol_version: ProtocolVersion::default(),
            capabilities: ServerCapabilities::default(),
            server_info: Implementation {
                name: "elicitate".to_string(),
                version: env!("CARGO_PKG_VERSION").to_string(),
            },
            instructions: Some(
                "elicitate_mcp renders a native OS popup and blocks until the human responds. \
                 Use it whenever you need a single, structured decision from the operator: \
                 confirmations, secrets, multi-choice selection, disambiguation. Returns typed \
                 JSON: {status: answered|cancelled|timed_out|failed, value?, notes?}."
                    .to_string(),
            ),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn params_default_timeout_is_600() {
        let p = ElicitateParams {
            title: "t".into(),
            question: String::new(),
            field: crate::spec::FieldSpec::Boolean {
                label: "?".into(),
                default: None,
            },
            notes: None,
            buttons: None,
            urgency: crate::spec::Urgency::default(),
            timeout_secs: default_timeout(),
            request_id: None,
        };
        let s: PromptSpec = p.into();
        assert_eq!(s.timeout_secs, 600);
    }
}
