[package]
name = "phenotype-retry"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license = "MIT OR Apache-2.0"
repository = "https://github.com/KooshaPari/PhenoProc"
description = "phenotype retry — Phenotype infrastructure crate (PhenoProc)"
documentation = "https://docs.rs/phenotype-retry"
keywords = ["phenotype", "pheno-proc"]
categories = ["development-tools"]
authors = ["kooshapari"]

[dependencies]
tokio = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["test-util", "macros", "rt", "time"] }
