[package]
name = "phenotype-mock"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Mock testing utilities for Phenotype"
license = "MIT OR Apache-2.0"
repository = "https://github.com/KooshaPari/PhenoProc"
documentation = "https://docs.rs/phenotype-mock"
keywords = ["phenotype", "pheno-proc", "mock"]
categories = ["development-tools::testing"]
authors = ["kooshapari"]

[dependencies]

[dev-dependencies]
