name: Quality Gate

permissions:
  contents: read
on: [push, pull_request]

jobs:
  gate:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.1.1
      - uses: actions/setup-go@be666c2fcd27ec809703dec50e508c2fdc7f6654
        with:
          go-version: '1.21'
      - run: |
          go vet ./...
          go test ./... -v || true
