[package]
name = "phenotype-async-traits"
version = "0.2.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Async traits for phenotype ecosystem"
repository = "https://github.com/KooshaPari/PhenoProc"
documentation = "https://docs.rs/phenotype-async-traits"
keywords = ["phenotype", "pheno-proc", "async"]
categories = ["asynchronous", "rust-patterns"]
authors = ["kooshapari"]

[lib]
path = "src/lib.rs"

[dependencies]
async-trait = "0.1"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
