name: Trufflehog Secrets Scan
on:
  push:
    branches: [main]
  pull_request:
jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0
      - uses: trufflehog/actions/setup@main
      - run: trufflehog github --only-verified --no-update
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
