name: OpenSSF Scorecard
on:
  schedule:
    # Mondays 02:00 UTC
    - cron: '0 2 * * 1'
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  security-events: write
  id-token: write

jobs:
  analysis:
    name: scorecard-analysis
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          persist-credentials: false

      - name: 'Run analysis'
        uses: ossf/scorecard-action@05b42c624433fc40578a4040d5cf5e36ddca8cde
        with:
          results_file: results.sarif
          results_format: sarif

      - name: 'Upload to code-scanning'
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        uses: github/codeql-action/upload-sarif@0daab03d71ff584ef619d027a3fd9146679c5d84
        with:
          sarif_file: results.sarif
