[package]
name = "pheno-errors-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.pheno-errors]
path = ".."

[[bin]]
name = "app_error_display"
path = "fuzz_targets/app_error_display.rs"
test = false
doc = false
bench = false
