---
name: Feature Request
description: Suggest a new feature
labels: enhancement
body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request
        
        **Is your feature request related to a problem?** Describe.
        
        **Describe the solution you'd like:** What you want to happen.
  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true
---
