[package]
name = "pheno-proc-shm"
version = "0.1.0"
edition = "2021"
description = "Shared memory processing for PhenoProc"
license = "MIT OR Apache-2.0"
repository = "https://github.com/KooshaPari/PhenoProc"
documentation = "https://docs.rs/pheno-proc-shm"
keywords = ["phenotype", "pheno-proc"]
categories = ["development-tools"]
authors = ["kooshapari"]

[dependencies]
thiserror = "2.0"
serde = { version = "1.0", features = ["derive"] }

[lib]
name = "pheno_proc_shm"
path = "src/lib.rs"
