on:
  workflow_dispatch:
permissions:
  contents: read

  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]

name: License Compliance
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true




jobs:
  cargo-deny:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v4
      - name: Install cargo-deny
        run: cargo install cargo-deny
      - name: Run cargo-deny
        run: cargo deny check
        continue-on-error: true

  fossa:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v4
      - name: Install FOSSA
        run: |
          curl -sSfL https://raw.githubusercontent.com/fossa-foss/fossa-cli/master/install.sh | sh
      - name: Run FOSSA
        run: fossa scan repository
        continue-on-error: true