[package]
name = "phenotype-policy-engine"
version = "0.2.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Policy engine for Phenotype"
repository = "https://github.com/KooshaPari/PhenoProc"
documentation = "https://docs.rs/phenotype-policy-engine"
keywords = ["phenotype", "pheno-proc", "policy"]
categories = ["authorization"]
authors = ["kooshapari"]

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tokio-test = { workspace = true }
