[package]
name = "phenotype-contracts"
version = "0.2.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Contract definitions for Phenotype"
repository = "https://github.com/KooshaPari/PhenoProc"
documentation = "https://docs.rs/phenotype-contracts"
keywords = ["phenotype", "pheno-proc", "contract"]
categories = ["development-tools"]
authors = ["kooshapari"]

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tokio-test = { workspace = true }
