//! Authentication port traits — hexagonal seams for token, audit, and credential operations.

use chrono::{DateTime, Utc};
use thiserror::Error;
use zeroize::ZeroizeOnDrop;

/// The action that triggered an audit event.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum AuditAction {
    /// An access token was successfully issued.
    TokenIssued,
    /// A token was successfully validated.
    TokenValidated,
    /// A token was rejected (expired, bad signature, wrong audience, malformed, or revoked).
    TokenRejected,
    /// A token was explicitly revoked.
    TokenRevoked,
    /// A refresh-token rotation completed successfully.
    TokenRotated,
    /// A secret was read from the vault.
    VaultRead,
    /// A secret was written in the vault.
    VaultWrite,
}

/// Outcome of an audited action.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum AuditOutcome {
    /// The operation completed successfully.
    Success,
    /// The operation failed.
    Failure,
}

/// A single immutable audit record. Must not contain secret material.
#[derive(Debug, Clone)]
pub struct AuditEvent {
    /// Wall-clock timestamp (UTC).
    pub timestamp: DateTime<Utc>,
    /// Optional caller identity.
    pub actor: Option<String>,
    /// Resource acted upon (e.g. JWT subject, vault key name).
    pub subject: String,
    /// The action that occurred.
    pub action: AuditAction,
    /// Whether the action succeeded or failed.
    pub outcome: AuditOutcome,
    /// Human-readable failure detail. Must not contain secrets.
    pub reason: Option<String>,
}

impl AuditEvent {
    /// Construct a successful event.
    pub fn success(actor: Option<String>, subject: impl Into<String>, action: AuditAction) -> Self {
        Self {
            timestamp: Utc::now(),
            actor,
            subject: subject.into(),
            action,
            outcome: AuditOutcome::Success,
            reason: None,
        }
    }

    /// Construct a failure event with an explanatory reason.
    pub fn failure(
        actor: Option<String>,
        subject: impl Into<String>,
        action: AuditAction,
        reason: impl Into<String>,
    ) -> Self {
        Self {
            timestamp: Utc::now(),
            actor,
            subject: subject.into(),
            action,
            outcome: AuditOutcome::Failure,
            reason: Some(reason.into()),
        }
    }
}

/// Port for emitting audit events.
pub trait AuditSink: Send + Sync {
    /// Emit a single audit event. Implementations should not propagate write errors.
    fn record(&self, event: AuditEvent);
}

/// Port for a JWT revocation store checked during token validation.
pub trait RevocationStore: Send + Sync {
    /// Revoke a token by its `jti`. `exp` is the token's Unix-timestamp expiry.
    fn revoke(&self, jti: &str, exp: i64);

    /// Returns `true` when `jti` is present in the deny-list.
    fn is_revoked(&self, jti: &str) -> bool;
}

/// Port for refresh-token rotation state.
pub trait RefreshTokenStore: Send + Sync {
    /// Register a new token family with its initial refresh-token JTI and expiry.
    fn insert_family(&self, family_id: &str, refresh_jti: &str, exp: i64);

    /// Attempt to advance the family to a new JTI.
    ///
    /// Returns `Ok(())` on success, `Err(true)` on reuse/compromise, `Err(false)` when
    /// the family does not exist or has expired.
    fn rotate(
        &self,
        family_id: &str,
        old_jti: &str,
        new_jti: &str,
        new_exp: i64,
    ) -> Result<(), bool>;

    /// Remove all records for a family.
    fn revoke_family(&self, family_id: &str);
}

/// Port for password hashing.
pub trait PasswordHasher: Send + Sync {
    /// Hash a password.
    fn hash(&self, password: &str) -> Result<String, String>;

    /// Verify a password against a hash.
    fn verify(&self, password: &str, hash: &str) -> bool;
}

/// A data-encryption key generated by a KMS.
#[derive(ZeroizeOnDrop)]
pub struct DataKey {
    /// Plaintext DEK (32 bytes).
    pub plaintext: [u8; 32],
    /// KEK-wrapped ciphertext DEK.
    pub wrapped: Vec<u8>,
}

/// Errors emitted by the KMS port.
#[derive(Debug, Error)]
pub enum KmsError {
    /// Key generation failed.
    #[error("Failed to generate data key")]
    GenerateFailed,
    /// Unwrap failed due to tampering or wrong KEK.
    #[error("Failed to unwrap data key: tampered or wrong KEK")]
    UnwrapFailed,
}

/// Port for key-management envelope-encryption operations.
pub trait KeyManagementService: Send + Sync {
    /// Generate a fresh random 256-bit DEK.
    fn generate_data_key(&self) -> Result<DataKey, KmsError>;

    /// Unwrap a previously wrapped DEK.
    fn decrypt_data_key(&self, wrapped: &[u8]) -> Result<[u8; 32], KmsError>;
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn audit_event_success_has_no_reason() {
        let event = AuditEvent::success(Some("actor".into()), "subject", AuditAction::TokenIssued);
        assert_eq!(event.outcome, AuditOutcome::Success);
        assert!(event.reason.is_none());
    }

    #[test]
    fn audit_event_failure_carries_reason() {
        let event = AuditEvent::failure(
            None,
            "jti-1",
            AuditAction::TokenRejected,
            "expired",
        );
        assert_eq!(event.outcome, AuditOutcome::Failure);
        assert_eq!(event.reason.as_deref(), Some("expired"));
    }
}
