"""JSONL audit trail emission for `pheno-worklog-schema` (ADR-032).

Implements the JSONL audit trail layer described in
`docs/adr/2026-06-17/ADR-032-pheno-worklog-schema-decision.md` § "JSONL
audit trail". The markdown `WORKLOG.md` is the canonical source of
truth (v2.0 / v2.1); this module derives the JSONL audit trail that
downstream tooling (CI ingestion, fleet analytics, 71-pillar audit)
consumes.

The audit trail is generated by the `pheno-worklog-schema` validator
and committed to `worklogs/{date}-L*.jsonl`. Each line is one entry;
the schema mirrors the markdown columns 1:1 plus `derived_at`
(ISO-8601 timestamp) and `tool_version`.

Output schema (13 fields, ADR-032):

    {
      "date":         "YYYY-MM-DD",    # from markdown `date` column
      "task_id":      "V11-CC-5",      # from markdown `task_id` column
      "layer":        "L8",            # from WorklogEntry.layer (V2 parser maps category → layer)
      "action":       "merge",         # from WorklogEntry.action ("merge" if status==merged else "commit")
      "files":        "src/lib.rs",    # joined WorklogEntry.files (v2.0/v2.1 markdown does not populate files)
      "notes":        "ADR-032",       # from markdown `notes` column
      "status":       "merged",        # from markdown `status` column
      "branch":       "chore/...",     # NOT in v2.1 markdown; emitted as "" (downstream derives from CI)
      "commit":       "3c64578",       # from markdown `commit_sha` column
      "pr":           283,             # from markdown `pr_number` column (int)
      "device":       "macbook",       # from markdown `device` column (v2.1 only)
      "derived_at":   "ISO-8601 Z",    # generated by emit_jsonl() at emission time
      "tool_version": "0.2.0",         # from pheno_worklog_schema.__version__ (overridable)
    }

Public API:
- emit_jsonl(worklog_path, output_path, derived_at=None, tool_version=None) -> int
- worklog_entry_to_json(entry, derived_at, tool_version) -> str (one JSONL line)

CLI:
- python3 -m pheno_worklog_schema.emit_jsonl WORKLOG.md OUTPUT.jsonl
                                         [--derived-at ISO] [--tool-version VER]
- pheno-worklog-emit (console-script, registered in pyproject.toml)
"""

from __future__ import annotations

import json
import sys
from datetime import date, datetime, timezone
from pathlib import Path
from typing import Any, Optional, Union

from pheno_worklog_schema.schema import WorklogEntry, parse_worklog


def _get_package_version() -> str:
    """Return the installed `pheno-worklog-schema` version.

    Imported lazily to break the circular dependency between
    `pheno_worklog_schema/__init__.py` (which exports `emit_jsonl`) and
    `emit_jsonl.py` (which needs `__version__`).
    """
    # Local import to avoid the circular dependency at module-load time.
    import pheno_worklog_schema  # noqa: WPS433 (intentional lazy import)
    return pheno_worklog_schema.__version__


# JSONL audit-trail schema field order (ADR-032 § "JSONL audit trail").
# Order is the canonical wire order for the JSONL file — consumers may
# rely on positional parsing, so changes here are breaking.
JSONL_FIELDS: tuple[str, ...] = (
    "date",
    "task_id",
    "layer",
    "action",
    "files",
    "notes",
    "status",
    "branch",
    "commit",
    "pr",
    "device",
    "derived_at",
    "tool_version",
)


def _now_iso8601_utc() -> str:
    """Return current UTC time as an ISO-8601 string with 'Z' suffix.

    Example: "2026-06-18T12:34:56Z"
    """
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _coerce_date(value: Union[date, str, None]) -> str:
    """Coerce a WorklogEntry.date to an ISO-8601 string.

    The v2 parser populates `date` with a `datetime.date` object; the
    v1 parser uses `date.fromisoformat` which also returns a `date`.
    We always emit a string for JSON-safety.
    """
    if value is None:
        return ""
    if isinstance(value, date):
        return value.isoformat()
    return str(value)


def _coerce_files(value: Any) -> str:
    """Coerce WorklogEntry.files to a comma-joined string.

    The v2 parser leaves `files=[]` (empty list); v1 splits on commas.
    For audit-trail emission we always emit a string (empty when no
    files are listed in the markdown).
    """
    if value is None:
        return ""
    if isinstance(value, (list, tuple)):
        return ",".join(str(x) for x in value if x)
    return str(value)


def worklog_entry_to_json(
    entry: WorklogEntry,
    derived_at: str,
    tool_version: str,
) -> str:
    """Convert one parsed `WorklogEntry` to a JSONL line (string).

    The output is a single line of JSON (no trailing newline), matching
    the schema documented in ADR-032 § "JSONL audit trail". Field order
    is canonical — see JSONL_FIELDS.

    Parameters
    ----------
    entry : WorklogEntry
        A single parsed worklog entry. Use `pheno_worklog_schema.parse_worklog`
        to obtain entries from a `WORKLOG.md` file.
    derived_at : str
        ISO-8601 UTC timestamp (`2026-06-18T12:34:56Z`) recording when
        the JSONL line was generated. Required.
    tool_version : str
        The `pheno-worklog-schema` package version that generated the
        line (e.g. `"0.2.0"`). Required.

    Returns
    -------
    str
        A single JSON object as a string, with no trailing newline.

    Notes
    -----
    Field mapping from `WorklogEntry` → JSONL:
    - `layer`   ← WorklogEntry.layer (set by the V2 parser from the
                  markdown `category` column; falls back to "L?" for v1)
    - `action`  ← WorklogEntry.action (V2 parser: "merge" if status is
                  "merged", else "commit")
    - `files`   ← WorklogEntry.files joined as a comma-separated string
                  (empty when the markdown has no files column)
    - `branch`  ← "" (not present in v2.1 markdown schema; consumers
                  derive from CI / git)
    - `commit`  ← WorklogEntry.commit_sha (or "" if None)
    - `pr`      ← WorklogEntry.pr_number (int or None → JSON null)
    """
    record: dict[str, Any] = {
        "date": _coerce_date(entry.date),
        "task_id": str(entry.task_id) if entry.task_id is not None else "",
        "layer": str(entry.layer) if entry.layer else "",
        "action": str(entry.action) if entry.action else "",
        "files": _coerce_files(entry.files),
        "notes": str(entry.notes) if entry.notes is not None else "",
        "status": str(entry.status) if entry.status else "",
        "branch": "",  # not in v2.1 markdown schema; downstream derives from CI
        "commit": str(entry.commit_sha) if entry.commit_sha else "",
        "pr": entry.pr_number,  # may be None → JSON null
        "device": str(entry.device) if entry.device is not None else "",
        "derived_at": str(derived_at),
        "tool_version": str(tool_version),
    }
    # `default=str` is a safety net for any field we missed (e.g. a
    # Path or enum leaked through).
    return json.dumps(record, default=str, ensure_ascii=False)


def emit_jsonl(
    worklog_path: Union[str, Path],
    output_path: Union[str, Path],
    derived_at: Optional[str] = None,
    tool_version: Optional[str] = None,
) -> int:
    """Parse `WORKLOG.md` and emit the JSONL audit trail to `output_path`.

    The JSONL file contains one JSON object per line, matching the
    schema documented in ADR-032 § "JSONL audit trail". Each line is
    terminated with `\\n` (the canonical JSONL wire format). An empty
    `WORKLOG.md` (no parseable rows) yields an empty output file.

    Parameters
    ----------
    worklog_path : str | Path
        Path to the `WORKLOG.md` file to parse. Accepts v1 (6-col),
        v2.0 (10-col), or v2.1 (11-col) formats.
    output_path : str | Path
        Path to write the JSONL output. Parent directories are NOT
        created — the caller is responsible for ensuring the
        destination directory exists.
    derived_at : str | None
        ISO-8601 UTC timestamp to record on every emitted line. If
        None, defaults to the current UTC time at emission.
    tool_version : str | None
        Package version string to record on every emitted line. If
        None, defaults to `pheno_worklog_schema.__version__`.

    Returns
    -------
    int
        Number of entries written. Zero for an empty `WORKLOG.md`.

    Examples
    --------
    >>> from pathlib import Path
    >>> n = emit_jsonl("WORKLOG.md", "worklogs/2026-06-18-T14-3.jsonl")
    >>> n
    12
    >>> import json
    >>> lines = Path("worklogs/2026-06-18-T14-3.jsonl").read_text().splitlines()
    >>> json.loads(lines[0])["task_id"]
    'V11-CC-5'
    """
    src = Path(worklog_path)
    dst = Path(output_path)

    if derived_at is None:
        derived_at = _now_iso8601_utc()
    if tool_version is None:
        tool_version = _get_package_version()

    entries = parse_worklog(src)

    # Write atomically-ish: encode all lines, then write in one go.
    # An empty WORKLOG.md yields an empty file (not "missing").
    payload = "".join(
        worklog_entry_to_json(e, derived_at=derived_at, tool_version=tool_version) + "\n"
        for e in entries
    )
    dst.write_text(payload, encoding="utf-8")

    return len(entries)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def _build_arg_parser():
    """Build an argparse parser for the `emit_jsonl` CLI entry point.

    Returned for testability; `main()` calls this and then invokes
    `parse_args()`.
    """
    import argparse

    parser = argparse.ArgumentParser(
        prog="pheno-worklog-emit",
        description=(
            "Emit a JSONL audit trail from a WORKLOG.md file (ADR-032). "
            "Each line is one parsed worklog entry; the schema mirrors "
            "the markdown columns plus derived_at + tool_version."
        ),
    )
    parser.add_argument(
        "worklog",
        type=Path,
        help="Path to the source WORKLOG.md file (v1 / v2.0 / v2.1).",
    )
    parser.add_argument(
        "output",
        type=Path,
        help="Path to write the JSONL output file.",
    )
    parser.add_argument(
        "--derived-at",
        type=str,
        default=None,
        help=(
            "ISO-8601 UTC timestamp to record on every emitted line "
            "(default: current UTC time at emission). "
            "Example: 2026-06-18T12:34:56Z"
        ),
    )
    parser.add_argument(
        "--tool-version",
        type=str,
        default=None,
        help=(
            "Tool version to record on every emitted line "
            "(default: pheno_worklog_schema.__version__)."
        ),
    )
    return parser


def main(argv: Optional[list[str]] = None) -> int:
    """CLI entry point: `python3 -m pheno_worklog_schema.emit_jsonl ...`.

    Returns the process exit code (0 on success, non-zero on error).
    """
    parser = _build_arg_parser()
    args = parser.parse_args(argv)

    if not args.worklog.exists():
        print(f"error: WORKLOG not found: {args.worklog}", file=sys.stderr)
        return 2

    try:
        n = emit_jsonl(
            args.worklog,
            args.output,
            derived_at=args.derived_at,
            tool_version=args.tool_version,
        )
    except FileNotFoundError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2

    print(f"emitted {n} entries → {args.output}", file=sys.stdout)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())