//! PR creation and review-fix loop (T048, T049).
//!
//! `create_pr` invokes `gh pr create` to open a pull request with a
//! structured description (FR-011).  `run_review_fix_loop` polls for
//! Coderabbit comments and re-dispatches the agent until approval or the
//! maximum cycle count is reached (FR-012).

use crate::ports::ReviewPort;
use crate::types::{
    AgentConfig, AgentTask, CiStatus, CommentSeverity, DomainError, ReviewComment,
    ReviewOutcome,
};
use std::path::Path;
use std::time::Duration;
use tokio::process::Command;
use tracing::{info, warn};

// ─── PR Description ───────────────────────────────────────────────────────────

/// Structured PR description satisfying FR-011.
#[derive(Debug, Clone)]
pub struct PrDescription {
    pub wp_id: String,
    pub wp_title: String,
    pub goal: String,
    pub fr_references: Vec<String>,
    pub acceptance_criteria: String,
    pub context_summary: String,
}

impl PrDescription {
    /// Render the description as a Markdown string for the PR body.
    #[must_use]
    pub fn to_markdown(&self) -> String {
        let fr_list = if self.fr_references.is_empty() {
            "- (none)".to_owned()
        } else {
            self.fr_references
                .iter()
                .map(|fr| format!("- {fr}"))
                .collect::<Vec<_>>()
                .join("\n")
        };

        format!(
            "## WP Goal\n{goal}\n\n\
             ## Functional Requirements\n{fr_list}\n\n\
             ## Acceptance Criteria\n{criteria}\n\n\
             ## Context\n{context}\n\n\
             ---\n\
             *Generated by AgilePlus spec-driven development engine*\n",
            goal = self.goal,
            fr_list = fr_list,
            criteria = self.acceptance_criteria,
            context = self.context_summary,
        )
    }
}

// ─── PR Creation ──────────────────────────────────────────────────────────────

/// Invoke `gh pr create` and return the PR URL on success.
///
/// Uses `worktree_path` as the working directory so `gh` picks up the correct
/// git remote automatically.
pub async fn create_pr(
    worktree_path: &Path,
    wp_id: &str,
    wp_title: &str,
    description: &PrDescription,
    target_branch: &str,
) -> Result<String, DomainError> {
    let title = format!("{wp_id}: {wp_title}");
    let body = description.to_markdown();

    let output = Command::new("gh")
        .arg("pr")
        .arg("create")
        .arg("--title")
        .arg(&title)
        .arg("--body")
        .arg(&body)
        .arg("--base")
        .arg(target_branch)
        .current_dir(worktree_path)
        .output()
        .await
        .map_err(|e| DomainError::PrCreationError(format!("gh spawn failed: {e}")))?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        return Err(DomainError::PrCreationError(format!(
            "gh pr create failed (exit {}): {stderr}",
            output.status.code().unwrap_or(-1)
        )));
    }

    let stdout = String::from_utf8_lossy(&output.stdout);
    let pr_url = parse_pr_url_from_gh_output(&stdout).ok_or_else(|| {
        DomainError::PrCreationError(format!(
            "could not parse PR URL from gh output: {stdout}"
        ))
    })?;

    info!(%pr_url, "PR created");
    Ok(pr_url)
}

fn parse_pr_url_from_gh_output(output: &str) -> Option<String> {
    // `gh pr create` prints the PR URL as the last non-empty line.
    output
        .lines()
        .filter(|l| l.contains("github.com") && l.contains("/pull/"))
        .last()
        .map(str::trim)
        .map(ToOwned::to_owned)
}

// ─── Review-fix Loop ──────────────────────────────────────────────────────────

/// Outcome of the full review-fix loop.
#[derive(Debug, Clone)]
pub struct ReviewLoopResult {
    pub approved: bool,
    pub cycles_used: u32,
    pub final_review_outcome: ReviewOutcome,
    pub final_ci_status: CiStatus,
    pub comment_history: Vec<Vec<ReviewComment>>,
}

/// Run the review-fix loop (FR-012).
///
/// Each cycle:
/// 1. Await a review decision from `review`.
/// 2. If approved → return success.
/// 3. If changes requested → format comments as agent instruction and re-dispatch.
/// 4. Await CI; feed logs to agent if failing.
/// 5. Repeat up to `max_cycles`.
///
/// On exhaustion a governance exception is logged and an error is returned.
pub async fn run_review_fix_loop(
    pr_url: &str,
    review: &dyn ReviewPort,
    _agent_config: &AgentConfig,
    task: &AgentTask,
    max_cycles: u32,
) -> Result<ReviewLoopResult, DomainError> {
    let mut comment_history: Vec<Vec<ReviewComment>> = Vec::new();
    let mut final_review_outcome = ReviewOutcome::Pending;
    let mut final_ci_status = CiStatus::Unknown;

    for cycle in 0..max_cycles {
        // Exponential backoff: 30s → 60s → 120s → 300s (cap).
        let poll_delay = backoff_secs(cycle);
        info!(cycle, poll_delay_secs = poll_delay, %pr_url, "awaiting review");
        tokio::time::sleep(Duration::from_secs(poll_delay)).await;

        let review_timeout = Duration::from_secs(300);
        let outcome = review
            .await_review(pr_url, review_timeout)
            .await
            .unwrap_or(ReviewOutcome::Pending);

        final_review_outcome = outcome.clone();

        match outcome {
            ReviewOutcome::Approved => {
                info!(cycle, "PR approved — loop complete");
                return Ok(ReviewLoopResult {
                    approved: true,
                    cycles_used: cycle + 1,
                    final_review_outcome: ReviewOutcome::Approved,
                    final_ci_status: CiStatus::Passing,
                    comment_history,
                });
            }

            ReviewOutcome::ChangesRequested => {
                let comments = review
                    .get_actionable_comments(pr_url)
                    .await
                    .unwrap_or_default();

                info!(
                    cycle,
                    num_comments = comments.len(),
                    "changes requested — feeding comments to agent"
                );

                comment_history.push(comments.clone());

                let instruction = format_review_comments_as_instruction(&comments);
                feed_instruction_to_agent(task, &instruction).await;
            }

            ReviewOutcome::Pending | ReviewOutcome::Dismissed => {
                warn!(cycle, ?outcome, "review still pending or dismissed — continuing");
            }
        }

        // Check CI status.
        let ci_timeout = Duration::from_secs(180);
        final_ci_status = review
            .await_ci(pr_url, ci_timeout)
            .await
            .unwrap_or(CiStatus::Unknown);

        if final_ci_status == CiStatus::Failing {
            warn!(cycle, "CI failing — notifying agent");
            let ci_instruction = format!("## CI Failure\n\nThe CI pipeline is failing. Please check the CI logs, fix the issues, commit, and push.\n\nPR: {pr_url}\n");
            feed_instruction_to_agent(task, &ci_instruction).await;
        }
    }

    // Governance exception: loop exhausted without approval.
    tracing::error!(
        max_cycles,
        %pr_url,
        final_review = ?final_review_outcome,
        ci_passing = ?final_ci_status,
        "governance exception: review loop exhausted without approval"
    );

    Err(DomainError::ReviewLoopExhausted {
        cycles: max_cycles,
    })
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

/// Compute the poll-backoff delay (in seconds) for a given cycle index.
/// Sequence: 30, 60, 120, 240, 300, 300 …
fn backoff_secs(cycle: u32) -> u64 {
    let base: u64 = 30;
    // Double each cycle but cap the shift at 4 to get 30*16=480 before min clamp.
    let delay = base * (1u64 << cycle.min(4));
    delay.min(300)
}

/// Format a slice of review comments into a markdown instruction for the agent.
pub fn format_review_comments_as_instruction(comments: &[ReviewComment]) -> String {
    if comments.is_empty() {
        return "## Review Feedback\n\nNo actionable comments found.\n".to_owned();
    }

    let mut lines = vec![
        "## Review Feedback - Fix Required\n".to_owned(),
        "Please fix all critical and major issues, then commit and push.\n".to_owned(),
    ];

    for c in comments {
        let severity = match c.severity {
            CommentSeverity::Critical => "Critical",
            CommentSeverity::Major => "Major",
            CommentSeverity::Minor => "Minor",
            CommentSeverity::Info => "Info",
        };
        let location = match c.line {
            Some(l) => format!("{}, Line {l}", c.file_path),
            None => c.file_path.clone(),
        };
        lines.push(format!("\n### File: {location} ({severity})\n> {}\n", c.body));
    }

    lines.concat()
}

/// Write the instruction to a file inside the worktree so the agent can pick it
/// up on its next invocation.  (Stdin is not available for async hand-off.)
async fn feed_instruction_to_agent(task: &AgentTask, instruction: &str) {
    let path = task
        .worktree_path
        .join(".agileplus-review-instruction.md");
    if let Err(e) = tokio::fs::write(&path, instruction).await {
        warn!("could not write review instruction file: {e}");
    } else {
        info!(
            path = %path.display(),
            "review instruction written for agent"
        );
    }
}

// ─── Tests ────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ports::ReviewPort;
    use crate::types::{AgentConfig, AgentTask, CiStatus, DomainError, ReviewOutcome};
    use async_trait::async_trait;
    use std::path::PathBuf;
    use std::sync::atomic::{AtomicU32, Ordering};
    use std::sync::Arc;

    // ── PrDescription ──────────────────────────────────────────────────────────

    #[test]
    fn pr_description_to_markdown_contains_all_sections() {
        let desc = PrDescription {
            wp_id: "WP08".to_owned(),
            wp_title: "Agent Dispatch".to_owned(),
            goal: "Implement agent dispatch".to_owned(),
            fr_references: vec!["FR-011".to_owned(), "FR-012".to_owned()],
            acceptance_criteria: "- [ ] PR created\n- [ ] Review loop runs".to_owned(),
            context_summary: "See spec.md §3".to_owned(),
        };

        let md = desc.to_markdown();
        assert!(md.contains("## WP Goal"));
        assert!(md.contains("Implement agent dispatch"));
        assert!(md.contains("FR-011"));
        assert!(md.contains("FR-012"));
        assert!(md.contains("## Acceptance Criteria"));
        assert!(md.contains("## Context"));
        assert!(md.contains("AgilePlus spec-driven development engine"));
    }

    #[test]
    fn pr_title_format_is_correct() {
        // Verify the format used in create_pr.
        let title = format!("{}: {}", "WP08", "Agent Dispatch Service");
        assert_eq!(title, "WP08: Agent Dispatch Service");
    }

    // ── format_review_comments_as_instruction ──────────────────────────────────

    #[test]
    fn format_comments_includes_severity_and_location() {
        let comments = vec![ReviewComment {
            file_path: "src/lib.rs".to_owned(),
            line: Some(42),
            severity: CommentSeverity::Critical,
            body: "Missing error handling".to_owned(),
        }];
        let instruction = format_review_comments_as_instruction(&comments);
        assert!(instruction.contains("src/lib.rs, Line 42 (Critical)"));
        assert!(instruction.contains("Missing error handling"));
    }

    #[test]
    fn format_empty_comments_returns_no_actionable_message() {
        let instruction = format_review_comments_as_instruction(&[]);
        assert!(instruction.contains("No actionable comments"));
    }

    // ── backoff_secs ──────────────────────────────────────────────────────────

    #[test]
    fn backoff_increases_exponentially_and_caps_at_300() {
        assert_eq!(backoff_secs(0), 30);   // 30 * 2^0 = 30
        assert_eq!(backoff_secs(1), 60);   // 30 * 2^1 = 60
        assert_eq!(backoff_secs(2), 120);  // 30 * 2^2 = 120
        assert_eq!(backoff_secs(3), 240);  // 30 * 2^3 = 240
        assert_eq!(backoff_secs(4), 300);  // 30 * 2^4 = 480 → capped at 300
        assert_eq!(backoff_secs(10), 300); // still capped
    }

    // ── Mock ReviewPort ───────────────────────────────────────────────────────

    /// Approves after `approve_after` cycles, requests changes before that.
    struct MockReview {
        approve_after: u32,
        call_count: Arc<AtomicU32>,
    }

    #[async_trait]
    impl ReviewPort for MockReview {
        async fn await_review(
            &self,
            _pr_url: &str,
            _timeout: Duration,
        ) -> Result<ReviewOutcome, DomainError> {
            let n = self.call_count.fetch_add(1, Ordering::SeqCst);
            if n >= self.approve_after {
                Ok(ReviewOutcome::Approved)
            } else {
                Ok(ReviewOutcome::ChangesRequested)
            }
        }

        async fn get_actionable_comments(
            &self,
            _pr_url: &str,
        ) -> Result<Vec<ReviewComment>, DomainError> {
            Ok(vec![ReviewComment {
                file_path: "src/lib.rs".to_owned(),
                line: Some(1),
                severity: CommentSeverity::Major,
                body: "Needs fix".to_owned(),
            }])
        }

        async fn await_ci(
            &self,
            _pr_url: &str,
            _timeout: Duration,
        ) -> Result<CiStatus, DomainError> {
            Ok(CiStatus::Passing)
        }
    }

    fn make_task(worktree: PathBuf) -> AgentTask {
        AgentTask {
            job_id: "test-job".to_owned(),
            feature_slug: "feat".to_owned(),
            wp_sequence: 8,
            wp_id: "WP08".to_owned(),
            prompt_path: worktree.join("prompt.md"),
            context_paths: vec![],
            worktree_path: worktree,
        }
    }

    #[tokio::test]
    async fn review_loop_approves_after_configured_cycles() {
        let tmp = tempfile::tempdir().unwrap();
        let task = make_task(tmp.path().to_path_buf());

        let call_count = Arc::new(AtomicU32::new(0));
        let review = MockReview {
            approve_after: 2, // approve on 3rd call (0-indexed: call 2)
            call_count: Arc::clone(&call_count),
        };

        let config = AgentConfig::default();
        let result = run_review_fix_loop("https://github.com/x/y/pull/1", &review, &config, &task, 5).await;

        assert!(result.is_ok());
        let outcome = result.unwrap();
        assert!(outcome.approved);
        assert_eq!(outcome.cycles_used, 3);
    }

    #[tokio::test]
    async fn review_loop_fails_when_max_cycles_exceeded() {
        let tmp = tempfile::tempdir().unwrap();
        let task = make_task(tmp.path().to_path_buf());

        let review = MockReview {
            approve_after: 999, // never approves
            call_count: Arc::new(AtomicU32::new(0)),
        };

        let config = AgentConfig::default();
        let result = run_review_fix_loop("https://github.com/x/y/pull/2", &review, &config, &task, 2).await;

        assert!(result.is_err());
        match result.unwrap_err() {
            DomainError::ReviewLoopExhausted { cycles } => assert_eq!(cycles, 2),
            other => panic!("unexpected error: {other}"),
        }
    }
}
