exclude:
  paths:
    - ".git/**"
    - "target/**"
    - "node_modules/**"
    - "*.sum"
    - "*.lock"
    - "dist/**"
    - ".github/workflows/**"
    - "**/*.yml"
    - "**/*.yaml"
include:
  files:
    - "**/*"
