package rollout

import (
	"fmt"
	"os/exec"
	"time"
)

const prRateLimit = 2 * time.Second

// CreateBootstrapPR creates a pull request for the bootstrapped governance artifacts.
// It uses the gh CLI with a standardized template. If dryRun is true, it prints
// what would be done without actually creating the PR.
func CreateBootstrapPR(repoPath, branch string, dryRun bool) error {
	if dryRun {
		fmt.Printf("[dry-run] would create PR in %s from branch %s\n", repoPath, branch)
		return nil
	}

	title := "chore: bootstrap governance artifacts"
	body := `## Bootstrap Governance Artifacts

This PR adds standardized governance and DX artifacts generated by pheno-cli:

- ` + "`mise.toml`" + `: Task automation configuration
- ` + "`.git/hooks/pre-commit`" + `: Commit message validation hook
- ` + "`.git/hooks/pre-push`" + `: Pre-push quality checks
- ` + "`.github/workflows/ci.yml`" + `: CI workflow
- ` + "`.github/workflows/release.yml`" + `: Release automation workflow
- ` + "`cliff.toml`" + `: Changelog generation configuration

Generated by [pheno-cli](https://github.com/KooshaPari/pheno-cli) bootstrap command.

## Review Checklist

- [ ] Review mise.toml tasks for correctness
- [ ] Verify CI workflow triggers
- [ ] Confirm release workflow matches registry settings
- [ ] Check risk profile settings
`

	cmd := exec.Command("gh", "pr", "create",
		"--title", title,
		"--body", body,
		"--head", branch,
		"--base", "main",
	)
	cmd.Dir = repoPath

	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("gh pr create failed in %s: %w\n%s", repoPath, err, string(output))
	}

	fmt.Printf("PR created in %s: %s\n", repoPath, string(output))

	// Rate limiting: pause between PR creations to avoid hitting API limits
	time.Sleep(prRateLimit)

	return nil
}
