//! PR description builder for work packages.
//!
//! Generates structured PR descriptions with WP goal, FR references,
//! acceptance criteria, and spec context.
//! Traceability: FR-011 / WP12-T070

use agileplus_domain::domain::feature::Feature;
use agileplus_domain::domain::work_package::WorkPackage;

/// Build a structured GitHub PR title for a work package.
pub fn build_pr_title(wp: &WorkPackage) -> String {
    let raw = format!("WP{:02}: {}", wp.id, wp.title);
    if raw.len() > 72 {
        format!("{}...", &raw[..69])
    } else {
        raw
    }
}

/// Build a structured Markdown PR description body.
pub fn build_pr_description(wp: &WorkPackage, feature: &Feature, spec_content: &str) -> String {
    let fr_refs = extract_fr_references(&wp.acceptance_criteria, spec_content);
    let file_scope_list = if wp.file_scope.is_empty() {
        "_(no specific files identified)_".to_string()
    } else {
        wp.file_scope
            .iter()
            .map(|f| format!("- `{f}`"))
            .collect::<Vec<_>>()
            .join("\n")
    };
    let checklist = build_acceptance_checklist(&wp.acceptance_criteria);

    format!(
        r"## Work Package: {title}

**Feature**: {friendly_name} (`{slug}`)
**WP ID**: {wp_id} | **Sequence**: {sequence}

### Goal
{criteria}

### Functional Requirements
{fr_refs}

### File Scope
{file_scope_list}

### Context
This PR implements work package WP{wp_id:02} of feature `{slug}`.
Full specification: `kitty-specs/{slug}/spec.md`
Implementation plan: `kitty-specs/{slug}/plan.md`

### Acceptance Criteria
{checklist}

---
*Generated by AgilePlus spec-driven development engine*
",
        title = wp.title,
        friendly_name = feature.friendly_name,
        slug = feature.slug,
        wp_id = wp.id,
        sequence = wp.sequence,
        criteria = wp.acceptance_criteria,
        fr_refs = fr_refs,
        file_scope_list = file_scope_list,
        checklist = checklist,
    )
}

/// Extract FR-NNN references from text and find their descriptions in spec.
fn extract_fr_references(text: &str, spec_content: &str) -> String {
    let mut fr_ids: Vec<String> = Vec::new();
    let mut start = 0;
    while let Some(pos) = text[start..].find("FR-") {
        let abs = start + pos;
        let rest = &text[abs + 3..];
        let end = rest
            .find(|c: char| !c.is_ascii_digit())
            .unwrap_or(rest.len());
        if end > 0 {
            fr_ids.push(format!("FR-{}", &rest[..end]));
        }
        start = abs + 3 + end.max(1);
    }
    fr_ids.dedup();

    if fr_ids.is_empty() {
        return "_(no FR references found in acceptance criteria)_".to_string();
    }

    let mut lines = Vec::new();
    for fr_id in &fr_ids {
        let description = find_fr_description(spec_content, fr_id)
            .unwrap_or_else(|| "(description not found in spec)".to_string());
        lines.push(format!("- **{fr_id}**: {description}"));
    }
    lines.join("\n")
}

/// Find the one-line description for an FR in spec content.
fn find_fr_description(spec: &str, fr_id: &str) -> Option<String> {
    for line in spec.lines() {
        if line.contains(fr_id) {
            // Strip leading markdown markers and the FR-NNN: prefix
            let cleaned = line
                .trim()
                .trim_start_matches('-')
                .trim_start_matches('*')
                .trim();
            // Remove bold markers
            let cleaned = cleaned.replace("**", "");
            if let Some(colon_pos) = cleaned.find(':') {
                return Some(cleaned[colon_pos + 1..].trim().to_string());
            }
            return Some(cleaned.to_string());
        }
    }
    None
}

/// Convert acceptance criteria text into a GitHub-compatible checklist.
fn build_acceptance_checklist(criteria: &str) -> String {
    criteria
        .lines()
        .filter(|l| !l.trim().is_empty())
        .map(|l| {
            let stripped = l
                .trim()
                .trim_start_matches('-')
                .trim_start_matches('*')
                .trim_start_matches('#')
                .trim();
            format!("- [ ] {stripped}")
        })
        .collect::<Vec<_>>()
        .join("\n")
}

#[cfg(test)]
mod tests {
    use super::*;
    use agileplus_domain::domain::feature::Feature;
    use agileplus_domain::domain::work_package::WorkPackage;

    fn make_feature() -> Feature {
        Feature::new("my-feature", "My Feature", [0u8; 32], Some("main"))
    }

    fn make_wp() -> WorkPackage {
        let mut wp = WorkPackage::new(
            1,
            "Implement auth module",
            1,
            "FR-001 login must work\nFR-002 logout must work",
        );
        wp.id = 9;
        wp.file_scope = vec!["src/auth.rs".into(), "src/main.rs".into()];
        wp
    }

    #[test]
    fn pr_title_basic() {
        let wp = make_wp();
        let title = build_pr_title(&wp);
        assert!(title.starts_with("WP09: "));
        assert!(title.contains("auth"));
    }

    #[test]
    fn pr_title_truncated() {
        let mut wp = make_wp();
        wp.title = "A".repeat(80);
        let title = build_pr_title(&wp);
        assert!(title.len() <= 72);
        assert!(title.ends_with("..."));
    }

    #[test]
    fn pr_description_contains_sections() {
        let feature = make_feature();
        let wp = make_wp();
        let spec = "## Functional Requirements\n- **FR-001**: Login must work\n- **FR-002**: Logout must work\n";
        let body = build_pr_description(&wp, &feature, spec);
        assert!(body.contains("## Work Package:"));
        assert!(body.contains("### Goal"));
        assert!(body.contains("### Functional Requirements"));
        assert!(body.contains("### File Scope"));
        assert!(body.contains("### Acceptance Criteria"));
        assert!(body.contains("- [ ]"));
        assert!(body.contains("src/auth.rs"));
    }

    #[test]
    fn extract_fr_refs_found() {
        let text = "FR-001 and FR-042 must pass";
        let spec = "- **FR-001**: Login feature\n- **FR-042**: Export feature\n";
        let result = extract_fr_references(text, spec);
        assert!(result.contains("FR-001"));
        assert!(result.contains("FR-042"));
        assert!(result.contains("Login feature"));
    }

    #[test]
    fn acceptance_checklist_format() {
        let criteria = "- First criterion\n- Second criterion\n";
        let checklist = build_acceptance_checklist(criteria);
        assert!(checklist.contains("- [ ] First criterion"));
        assert!(checklist.contains("- [ ] Second criterion"));
    }
}
