[package]
name = "phenotype-state-machine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Generic finite state machine for Phenotype"
license = "MIT OR Apache-2.0"
repository = "https://github.com/KooshaPari/PhenoProc"
documentation = "https://docs.rs/phenotype-state-machine"
keywords = ["phenotype", "pheno-proc", "state-machine"]
categories = ["data-structures"]
authors = ["kooshapari"]

[dependencies]
thiserror = { workspace = true }

[dev-dependencies]
