"""Pydantic models for 4SGM MCP Server."""

from .product import (
    GetProductInput,
    ProductResponse,
    SearchProductsInput,
    SearchProductsResponse,
    GetInventoryInput,
    InventoryResponse,
    UpdateInventoryInput,
    UpdateInventoryResponse,
    GetPricingInput,
    PricingResponse,
    ApplyDiscountInput,
    DiscountResponse,
)
from .cart import (
    CreateCartInput,
    CartResponse,
    CartItemResponse,
    AddToCartInput,
    AddToCartResponse,
    RemoveFromCartInput,
    RemoveFromCartResponse,
    CartItem,
    CalculateCartTotalInput,
    CartTotalResponse,
    ValidateCartInput,
    CartValidationResponse,
)
from .order import (
    CreateOrderInput,
    OrderResponse,
)
from .shipping import (
    ShippingCalculationInput,
    ShippingCalculationResponse,
    CarrierOption,
    ShippingMethodInput,
    ShippingMethodResponse,
    TrackingInput,
    TrackingEvent,
    TrackingResponse,
    DeliveryEstimateInput,
    DeliveryEstimateResponse,
)
from .pricing import (
    BulkPricingInput,
    BulkPricingResponse,
    CouponInput,
    CouponResponse,
    PromotionResponse,
    SavingsCalculationInput,
    SavingsCalculationResponse,
)
from .customer import (
    CustomerHistoryInput,
    OrderRecord,
    CustomerHistoryResponse,
    CustomerPreferencesInput,
    CustomerPreferencesResponse,
    SavePreferencesInput,
)
from .rfq import (
    RFQItem,
    CreateRFQInput,
    CreateRFQResponse,
    GetRFQStatusInput,
    GetRFQStatusResponse,
    AcceptRFQInput,
    AcceptRFQResponse,
)

__all__ = [
    # Product
    "GetProductInput",
    "ProductResponse",
    "SearchProductsInput",
    "SearchProductsResponse",
    "GetInventoryInput",
    "InventoryResponse",
    "UpdateInventoryInput",
    "UpdateInventoryResponse",
    "GetPricingInput",
    "PricingResponse",
    "ApplyDiscountInput",
    "DiscountResponse",
    # Cart
    "CreateCartInput",
    "CartResponse",
    "CartItemResponse",
    "AddToCartInput",
    "AddToCartResponse",
    "RemoveFromCartInput",
    "RemoveFromCartResponse",
    "CartItem",
    "CalculateCartTotalInput",
    "CartTotalResponse",
    "ValidateCartInput",
    "CartValidationResponse",
    # Order
    "CreateOrderInput",
    "OrderResponse",
    # Shipping
    "ShippingCalculationInput",
    "ShippingCalculationResponse",
    "CarrierOption",
    "ShippingMethodInput",
    "ShippingMethodResponse",
    "TrackingInput",
    "TrackingEvent",
    "TrackingResponse",
    "DeliveryEstimateInput",
    "DeliveryEstimateResponse",
    # Pricing
    "BulkPricingInput",
    "BulkPricingResponse",
    "CouponInput",
    "CouponResponse",
    "PromotionResponse",
    "SavingsCalculationInput",
    "SavingsCalculationResponse",
    # Customer
    "CustomerHistoryInput",
    "OrderRecord",
    "CustomerHistoryResponse",
    "CustomerPreferencesInput",
    "CustomerPreferencesResponse",
    "SavePreferencesInput",
    # RFQ
    "RFQItem",
    "CreateRFQInput",
    "CreateRFQResponse",
    "GetRFQStatusInput",
    "GetRFQStatusResponse",
    "AcceptRFQInput",
    "AcceptRFQResponse",
]
