"""Generated gRPC stubs for AgilePlus.

Implements FR-053 to FR-057. See WP00.

Stubs are generated by `buf generate` into `src/gen/`.
Re-export generated modules here for downstream consumption.
"""

import os
import sys

# Add the generated stubs directory to sys.path so they can find each other
# (e.g. core_pb2.py needs to find common_pb2.py via 'from agileplus.v1 import ...')
gen_path = os.path.join(os.path.dirname(__file__), "gen")
if gen_path not in sys.path:
    sys.path.insert(0, gen_path)

# Generated stubs will be available after running `buf generate`.
# Import paths depend on buf codegen output structure.
# Example (after generation):
#   from agileplus_proto.gen.agileplus.v1 import common_pb2
#   from agileplus_proto.gen.agileplus.v1 import core_pb2
#   from agileplus_proto.gen.agileplus.v1 import core_pb2_grpc
#   from agileplus_proto.gen.agileplus.v1 import agents_pb2
#   from agileplus_proto.gen.agileplus.v1 import agents_pb2_grpc
#   from agileplus_proto.gen.agileplus.v1 import integrations_pb2
#   from agileplus_proto.gen.agileplus.v1 import integrations_pb2_grpc
