name: Fuzzing

on:
  push:
    paths:
      - '**.rs'
      - '**.go'
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read

jobs:
  cargo-fuzz:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Install Rust
        uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8
      - name: Install cargo-fuzz
        run: cargo install cargo-fuzz || true
      - name: Run fuzzing
        run: cargo fuzz run all || true
        continue-on-error: true