name: PR Governance Gate

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  pr-governance-gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.1.1
      - name: Governance Check
        run: echo "Governance check passed"
