[package]
name = "phenotype-error-core"
version = "0.2.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Core error types for Phenotype"
repository = "https://github.com/KooshaPari/PhenoProc"
documentation = "https://docs.rs/phenotype-error-core"
keywords = ["phenotype", "pheno-proc", "error"]
categories = ["rust-patterns", "data-structures"]
authors = ["kooshapari"]

[dependencies]
thiserror = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
anyhow = { workspace = true }

[dev-dependencies]
